apiVersion: v1
kind: ConfigMap
metadata:
  name: automarket-config
  namespace: automarket
data:
  DB_URL: "jdbc:postgresql://postgres:5432/automarket"
  DB_USERNAME: "automarket"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka.automarket.svc.cluster.local:9092"
  MAIL_PROVIDER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_FROM: "noreply@automarket.com"
  FRONTEND_URL: "http://automarket.local"
  STORAGE_PROVIDER: "local"
  LOCAL_UPLOAD_DIR: "/app/uploads"
  LOCAL_BASE_URL: "http://automarket.local/uploads"
  STRIPE_ENABLED: "false"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  LISTING_SERVICE_URL: "http://listing-service:8082"
  BLOG_SERVICE_URL: "http://blog-service:8083"
  INQUIRY_SERVICE_URL: "http://inquiry-service:8084"
  PAYMENT_SERVICE_URL: "http://payment-service:8086"
