apiVersion: v1
kind: Secret
metadata:
  name: automarket-secret
  namespace: automarket
type: Opaque
stringData:
  DB_PASSWORD: "secret"
  JWT_SECRET: "change-this-secret-in-production-must-be-at-least-32-chars"
  RABBITMQ_PASSWORD: "secret"
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
