apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  namespace: automarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reference-service
  template:
    metadata:
      labels:
        app: reference-service
    spec:
      containers:
        - name: reference-service
          image: automarket/automarket-reference-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: automarket-config
            - secretRef:
                name: automarket-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
